version: '3.7'

services:
  currencies-updater:
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    container_name: currencies-updater
    image: chicker/currencies-updater:latest
    restart: "no"
    tty: true
    network_mode: "host"
    depends_on: [postgres]
  postgres:
    image: postgres:11.10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=currencies
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5